FROM balenalib/jetson-agx-orin-devkit-ubuntu:focal-run-20221215

# Don't prompt with any configuration questions
ENV DEBIAN_FRONTEND noninteractive

# Install some utils
RUN apt-get update && apt-get install -y lbzip2 git wget unzip jq xorg tar \
    python3 libegl1 binutils xz-utils zstd libglu1-mesa libglu1-mesa-dev \
    freeglut3 freeglut3-dev

# Install CUDA
RUN apt-get install -y nvidia-l4t-cuda nvidia-cuda cuda-samples-11-4

# Set paths
ENV CUDA_HOME=/usr/local/cuda-11.4

# Build some (but not all) of the sample apps
RUN \
    export SMS=87 && \
    cd /usr/local/cuda-11.4/samples/0_Simple/clock/ && make -j8 && \
    cd /usr/local/cuda-11.4/samples/1_Utilities/deviceQuery/ && make -j8 && \
    cd /usr/local/cuda-11.4/samples/2_Graphics/simpleTexture3D/ && make -j8 && \
    cd /usr/local/cuda-11.4/samples/2_Graphics/simpleGL/ && make -j8 && \
    cd /usr/local/cuda-11.4/samples/3_Imaging/postProcessGL/ && make -j8 && \
    cd /usr/local/cuda-11.4/samples/5_Simulations/smokeParticles && make -j8

ENV UDEV=1

# Download and install BSP binaries for L4T 35.5.0
RUN \
    cd /tmp/ && wget https://developer.nvidia.com/embedded/l4t/r35_release_v5.0/release/jetson_linux_r35.5.0_aarch64.tbz2 && \
    tar xf jetson_linux_r35.5.0_aarch64.tbz2 && \
    cd Linux_for_Tegra && \
    sed -i 's/config.tbz2\"/config.tbz2\" --exclude=etc\/hosts --exclude=etc\/hostname/g' apply_binaries.sh && \
    sed -i 's/install --owner=root --group=root \"${QEMU_BIN}\" \"${L4T_ROOTFS_DIR}\/usr\/bin\/\"/#install --owner=root --group=root \"${QEMU_BIN}\" \"${L4T_ROOTFS_DIR}\/usr\/bin\/\"/g' nv_tegra/nv-apply-debs.sh && \
    sed -i 's/chroot . \//  /g' nv_tegra/nv-apply-debs.sh && \
    ./apply_binaries.sh -r / --target-overlay && cd .. \
    rm -rf Linux_for_Tegra && \
    echo "/usr/lib/aarch64-linux-gnu/tegra" > /etc/ld.so.conf.d/nvidia-tegra.conf && ldconfig
    
WORKDIR /usr/local/cuda-11.4/samples/bin/aarch64/linux/release

CMD [ "sleep", "infinity" ]
